# Generated by Django 5.0.3 on 2025-05-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('salle', models.CharField(max_length=50)),
                ('jury', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
