# Generated by Django 5.0.3 on 2025-05-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenance', '0003_alter_soutenance_salle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutenance',
            name='heure',
        ),
        migrations.AddField(
            model_name='soutenance',
            name='heure_debut',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='heure_fin',
            field=models.TimeField(null=True),
        ),
    ]
