# Generated by Django 5.0.3 on 2025-05-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenance', '0004_remove_soutenance_heure_soutenance_heure_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='annee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='specialite',
            field=models.IntegerField(null=True),
        ),
    ]
