# Generated by Django 5.2 on 2025-05-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenance', '0005_soutenance_annee_soutenance_specialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='jury',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
