# Generated by Django 5.0.3 on 2025-05-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenance', '0005_soutenance_annee_soutenance_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='annee_academique',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
