# Generated by Django 5.0.3 on 2025-05-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soutenance', '0006_soutenance_annee_academique_soutenance_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='jury',
            field=models.JSONField(null=True),
        ),
    ]
