# Generated by Django 5.2 on 2025-05-25 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soutenance', '0006_alter_soutenance_jury'),
        ('soutenance', '0007_alter_soutenance_jury'),
    ]

    operations = [
    ]
