# Generated by Django 5.0.3 on 2025-04-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100, null=True, unique=True)),
                ('theme_id', models.IntegerField(null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
