# Generated by Django 5.0.3 on 2025-04-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assigned_by_admin_id',
            field=models.IntegerField(null=True),
        ),
    ]
