# Generated by Django 5.0.4 on 2025-05-26 18:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='annee_academique',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_by_admin_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='date_soumission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assignment',
            name='encadrant',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='soutenance_valide',
            field=models.BooleanField(default=False),
        ),
    ]
