# Generated by Django 5.2 on 2025-05-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0002_assignment_annee_academique_assignment_archived_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='date_soumission',
        ),
    ]
