# Generated by Django 5.0.3 on 2025-05-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0002_assignment_assigned_by_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='encadrant',
            field=models.IntegerField(null=True),
        ),
    ]
