# Generated by Django 5.2 on 2025-05-26 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0003_remove_assignment_date_soumission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date_soumission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
