# Generated by Django 5.0.3 on 2025-05-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0003_assignment_encadrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='soutenance_valide',
            field=models.BooleanField(default=False),
        ),
    ]
