# Generated by Django 5.0.3 on 2025-05-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0004_assignment_soutenance_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='annee_academique',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
