# Generated by Django 5.0.3 on 2025-05-23 23:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectation', '0005_assignment_annee_academique_assignment_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date_soumission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
