# Generated by Django 5.0.3 on 2025-03-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('secteur_activite', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('wilaya', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('representant_nom', models.CharField(max_length=255)),
                ('representant_poste', models.CharField(max_length=255)),
                ('representant_email', models.EmailField(max_length=254, unique=True)),
                ('representant_telephone', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
