<<<<<<< HEAD
# Generated by Django 5.0.3 on 2025-05-23 22:02
=======
# Generated by Django 5.0.4 on 2025-05-23 11:40
>>>>>>> Ayet

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('year', models.CharField(editable=False, max_length=9, unique=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='specialite',
            name='annee',
        ),
        migrations.AddField(
            model_name='annee',
            name='has_specialite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salle',
            name='nom_salle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specialite',
            name='abv',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('secteur_activite', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('wilaya', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('representant_nom', models.CharField(max_length=255)),
                ('representant_prenom', models.CharField(max_length=255, null=True)),
                ('representant_poste', models.CharField(max_length=255)),
                ('representant_email', models.EmailField(max_length=254, unique=True)),
                ('representant_telephone', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('compte_utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parametre_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('startup', 'startup'), ('binome', 'binome'), ('monome', 'monome')], max_length=20, null=True)),
                ('nbr_min', models.IntegerField(null=True)),
                ('nbr_max', models.IntegerField(null=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('annee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.annee')),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.anneeacademique')),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('depot_theme', 'Dépôt des Thèmes'), ('soutenance', 'Soutenance')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('archived', models.BooleanField(default=False)),
                ('annee_academique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.anneeacademique')),
            ],
        ),
    ]
