# Generated by Django 5.1.7 on 2025-05-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_anneeacademique_remove_specialite_annee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anneeacademique',
            name='archived',
        ),
    ]
