# Generated by Django 5.0.3 on 2025-03-10 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_entreprise_compte_utilisateur_entreprise_motif_refus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='compte_utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
