# Generated by Django 5.1.7 on 2025-05-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_anneeacademique_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneeacademique',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
