# Generated by Django 5.0.3 on 2025-03-23 14:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_entreprise_compte_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='representant_prenom',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_profil',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_profil'),
        ),
    ]
