# Generated by Django 5.0.3 on 2025-04-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_photo_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='representant_prenom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_profil',
        ),
    ]
