# Generated by Django 5.2 on 2025-04-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_user_profile_picture_user_photo_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='nom_salle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
