# Generated by Django 5.0.3 on 2025-04-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_user_profile_picture_user_photo_profil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialite',
            name='annee',
        ),
    ]
