# Generated by Django 5.2 on 2025-04-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_salle_nom_salle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialite',
            name='annee',
        ),
    ]
