# Generated by Django 5.0.3 on 2025-04-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_specialite_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
