# Generated by Django 5.0.3 on 2025-04-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_enseignant_grade_enseignant_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='representant_prenom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
