# Generated by Django 5.2 on 2025-04-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_enseignant_grade_enseignant_matricule')
    ]

    operations = [
    ]
