# Generated by Django 5.2 on 2025-04-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_salle_nom_salle'),
        ('api', '0013_merge_20250426_1536'),
    ]

    operations = [
    ]
