# Generated by Django 5.2 on 2025-04-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_0011_salle_nom_salle_0013_merge_20250426_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='representant_prenom',
            field=models.CharField(default='Inconnu', max_length=255),
            preserve_default=False,
        ),
    ]
