# Generated by Django 5.2 on 2025-04-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_entreprise_representant_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='annee',
            name='has_specialite',
            field=models.BooleanField(default=False),
        ),
    ]
