# Generated by Django 5.0.3 on 2025-04-26 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_entreprise_representant_prenom'),
        ('api', '0015_entreprise_representant_prenom'),
    ]

    operations = [
    ]
