# Generated by Django 5.2 on 2025-04-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_annee_has_specialite'),
        ('api', '0016_merge_20250426_2319'),
    ]

    operations = [
    ]
