# Generated by Django 5.0.3 on 2025-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20250428_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('depot_theme', 'Dépôt des Thèmes'), ('soutenance', 'Soutenance')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Période',
                'verbose_name_plural': 'Périodes',
            },
        ),
    ]
