# Generated by Django 5.0.3 on 2025-04-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_periode'),
    ]

    operations = [
        migrations.AddField(
            model_name='annee',
            name='nbr_personne',
            field=models.IntegerField(null=True),
        ),
    ]
