# Generated by Django 5.0.3 on 2025-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_annee_nbr_personne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annee',
            old_name='nbr_personne',
            new_name='nbr_personne_max',
        ),
        migrations.AddField(
            model_name='annee',
            name='nbr_personne_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='specialite',
            name='abv',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
