# Generated by Django 5.0.3 on 2025-05-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_nbr_personne_annee_nbr_personne_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('startup', 'startup'), ('binome', 'binome'), ('monome', 'monome')], max_length=20, null=True)),
                ('nbr_min', models.IntegerField(null=True)),
                ('nbr_max', models.IntegerField(null=True)),
                ('annee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.annee')),
            ],
        ),
    ]
