# Generated by Django 5.0.3 on 2025-05-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_parametre_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annee',
            name='nbr_personne_max',
        ),
        migrations.RemoveField(
            model_name='annee',
            name='nbr_personne_min',
        ),
    ]
