# Generated by Django 5.0.3 on 2025-05-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_annee_nbr_personne_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre_group',
            name='date_soumission',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
