# Generated by Django 5.0.3 on 2025-05-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_parametre_group_date_soumission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametre_group',
            name='date_soumission',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
