# Generated by Django 5.0.3 on 2025-05-21 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_anneeacademique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periode',
            options={},
        ),
        migrations.AddField(
            model_name='periode',
            name='annee_academique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.anneeacademique'),
        ),
        migrations.AddField(
            model_name='periode',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
