# Generated by Django 5.0.3 on 2025-05-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_periode_options_periode_annee_academique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre_group',
            name='annee_academique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.anneeacademique'),
        ),
        migrations.AddField(
            model_name='parametre_group',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
