# Generated by Django 5.0.4 on 2025-05-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_entreprise_representant_prenom'),
        ('api', '0017_merge_20250428_1243'),
        ('api', '0027_parametre_group_annee_academique_and_more'),
    ]

    operations = [
    ]
