# Generated by Django 5.1.7 on 2025-03-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('resume', models.TextField()),
                ('outils_et_language', models.TextField()),
                ('plan_travail', models.TextField()),
                ('livrable', models.TextField(blank=True, null=True)),
                ('annee_academique_id', models.IntegerField()),
                ('valide', models.BooleanField(default=False)),
                ('reserve', models.BooleanField(default=False)),
                ('motif', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeSpecialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite_id', models.IntegerField()),
                ('priorite', models.IntegerField()),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_specialites', to='creationTheme.theme')),
            ],
            options={
                'unique_together': {('theme', 'specialite_id')},
            },
        ),
    ]
