# Generated by Django 5.1.7 on 2025-03-23 07:29

import creationTheme.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationTheme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='theme',
            name='annee_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='enseignant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='entreprise_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='specialite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='annee_academique_id',
            field=models.CharField(default=creationTheme.models.generate_annee_academique_id, editable=False, max_length=9),
        ),
        migrations.AlterField(
            model_name='theme',
            name='reserve',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='valide',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='priorite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creationTheme.priority'),
        ),
        migrations.DeleteModel(
            name='ThemeSpecialite',
        ),
    ]
