# Generated by Django 5.1.7 on 2025-03-15 09:54

import creationTheme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationTheme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='enseignant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='entreprise_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='themespecialite',
            name='annee_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='annee_academique_id',
            field=models.CharField(default=creationTheme.models.generate_annee_academique_id, editable=False, max_length=9),
        ),
        migrations.AlterField(
            model_name='theme',
            name='reserve',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='valide',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='themespecialite',
            name='priorite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='themespecialite',
            name='specialite_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
