# Generated by Django 5.1.7 on 2025-03-12 06:47

import creationTheme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationTheme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='annee_academique_id',
            field=models.IntegerField(blank=True, null=True, validators=[creationTheme.models.validate_annee_academique_id]),
        ),
        migrations.AlterField(
            model_name='themespecialite',
            name='priorite',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='themespecialite',
            name='specialite_id',
            field=models.IntegerField(blank=True, null=True, validators=[creationTheme.models.validate_specialite_id]),
        ),
    ]
