# Generated by Django 5.2 on 2025-05-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationTheme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='annee_academique_id',
        ),
        migrations.AddField(
            model_name='theme',
            name='annee_academique',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='annee_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='theme',
            name='convention',
            field=models.FileField(blank=True, null=True, upload_to='conventions/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='enseignant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='entreprise_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='numberOfGrp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='option_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='theme',
            name='priorities',
            field=models.JSONField(blank=True, default=list, help_text="Liste d'objets avec format: [{'priorite': 1, 'specialite_id': 5}, ...]", null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='livrable',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='outils_et_language',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='plan_travail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='reserve',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='resume',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='titre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='theme',
            name='valide',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='ThemeSpecialite',
        ),
    ]
