# Generated by Django 5.2 on 2025-04-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationTheme', '0002_priority_theme_annee_id_theme_enseignant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='option_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
