# Generated by Django 5.0.3 on 2025-05-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creationTheme', '0002_remove_theme_annee_academique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='convention',
        ),
    ]
