# Generated by Django 5.0.3 on 2025-05-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationTheme', '0003_remove_theme_convention'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='convention',
            field=models.FileField(blank=True, null=True, upload_to='conventions/'),
        ),
    ]
