# Generated by Django 5.2 on 2025-04-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationTheme', '0003_theme_option_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='outils_et_language',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='plan_travail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='resume',
            field=models.TextField(null=True),
        ),
    ]
