# Generated by Django 5.2 on 2025-04-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationTheme', '0004_alter_theme_outils_et_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='priorite',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='specialite_id',
        ),
        migrations.AddField(
            model_name='theme',
            name='priorities',
            field=models.JSONField(blank=True, default=list, help_text="Liste d'objets avec format: [{'priorite': 1, 'specialite_id': 5}, ...]", null=True),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
