# Generated by Django 5.2 on 2025-04-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationTheme', '0005_remove_theme_priorite_remove_theme_specialite_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='numberOfGrp',
            field=models.IntegerField(null=True),
        ),
    ]
