# Generated by Django 5.1.7 on 2025-05-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationTheme', '0006_theme_numberofgrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='convention',
            field=models.FileField(blank=True, null=True, upload_to='conventions/'),
        ),
    ]
