# Generated by Django 5.1.7 on 2025-05-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationTheme', '0007_theme_convention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='titre',
            field=models.TextField(),
        ),
    ]
