# Generated by Django 5.1.7 on 2025-05-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creationTheme', '0008_alter_theme_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='livrable',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='outils_et_language',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='plan_travail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='resume',
            field=models.TextField(default=''),
        ),
    ]
